### ISSUE TITLE
The size specified at initialization differs from the size of the image.

### ISSUE THREAD

**Issue by mminn** [waynejo/android-ndk-gif#22]
I am getting the error - The size specified at initialization differs from the size of the image.
 expected:(425, 450) actual:(850,900).

Below is the code and both input images (p1,p2) have same size(425,450).

        int delayMs=100;
        GifEncoder gifEncoder = new GifEncoder();
        
            gifEncoder.init(425, 450, dabsolutePath, GifEncoder.EncodingType.ENCODING_TYPE_NORMAL_LOW_MEMORY);
    

        Bitmap bitmap1,bitmap2;
        bitmap1= BitmapFactory.decodeResource(getResources(),R.drawable.p1);
        bitmap2= BitmapFactory.decodeResource(getResources(),R.drawable.p2);

        gifEncoder.encodeFrame(bitmap1, delayMs);
        gifEncoder.encodeFrame(bitmap2, delayMs);       

        gifEncoder.close();

**Comment by ajaystha005** [comment]
The bitmap size must be same as define size.
In your case, all the bitmap size must be 425 X 450

**Comment by mminn** [comment]
As i mentioned in the issue description, all inputs bitmap1,bitmap2 are same size, 425x450.

**Comment by ajaystha005** [comment]
I also had the same issue but it works after I made the same size.

You also can look for FFMpeg.
https://github.com/WritingMinds/ffmpeg-android

**Comment by mminn** [comment]
ok. But, as i said,  all my input bitmap images already have same size. Could you please let me know what kind of changes you have done when you faced this issue?

**Comment by mminn** [comment]
I have changed the size to 850x900 in init and it solved the issue.

**Comment by waynejo** [comment]
Thanks for waiting.
"BitmapFactory.decodeResource" function will change the image size depending on dpi.
So, I think you used a scaled image.

1) Please use the options below.
BitmapFactory.Options bmpOp  = new BitmapFactory.Options();
bmpOp.inScaled = false;
bmpOp.inDensity = dpi;
BitmapFactory.decodeResource(...., ...., bmpOp);

2) Or just put the image in the "drawable-nodpi" folder instead of "drawable - ... dpi".

3) Or when you init, use bitmap1.getWidth(), bitmap1.getHeight()


Thanks.
